"""initial_schema

Revision ID: 001_initial
Revises: 
Create Date: 2026-04-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all initial tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Raw listings table
    op.create_table(
        'raw_listings',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source_portal', sa.String(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('scrape_timestamp', sa.String(), nullable=False),
        sa.Column('raw_data', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_listings_source_portal', 'raw_listings', ['source_portal'])
    op.create_index('idx_raw_listings_scrape_timestamp', 'raw_listings', ['scrape_timestamp'])
    op.create_index('idx_raw_listings_source_id', 'raw_listings', ['source_id'])
    
    # Clean listings table
    op.create_table(
        'clean_listings',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source_portal', sa.String(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('scrape_timestamp', sa.String(), nullable=False),
        sa.Column('titulo', sa.Text(), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('preco_pedido', sa.Float(), nullable=False),
        sa.Column('area_util_m2', sa.Float(), nullable=False),
        sa.Column('quartos', sa.Integer(), nullable=False),
        sa.Column('casas_banho', sa.Integer(), nullable=True),
        sa.Column('morada_raw', sa.Text(), nullable=True),
        sa.Column('freguesia', sa.String(), nullable=True),
        sa.Column('concelho', sa.String(), nullable=True),
        sa.Column('distrito', sa.String(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lon', sa.Float(), nullable=True),
        sa.Column('estado', sa.String(), nullable=True),
        sa.Column('ano_construcao', sa.Integer(), nullable=True),
        sa.Column('cert_energetico', sa.String(), nullable=True),
        sa.Column('tipologia', sa.String(), nullable=True),
        sa.Column('fotos_urls', sa.JSON(), nullable=True),
        sa.Column('num_fotos', sa.Integer(), nullable=True),
        sa.Column('agencia', sa.String(), nullable=True),
        sa.Column('preco_por_m2', sa.Float(), nullable=True),
        sa.Column('ine_preco_medio_m2', sa.Float(), nullable=True),
        sa.Column('ine_tendencia_mensal', sa.Float(), nullable=True),
        sa.Column('dist_metro_m', sa.Float(), nullable=True),
        sa.Column('dist_escola_m', sa.Float(), nullable=True),
        sa.Column('dist_comercio_m', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clean_listings_source_portal', 'clean_listings', ['source_portal'])
    op.create_index('idx_clean_listings_freguesia', 'clean_listings', ['freguesia'])
    op.create_index('idx_clean_listings_concelho', 'clean_listings', ['concelho'])
    op.create_index('idx_clean_listings_preco', 'clean_listings', ['preco_pedido'])
    op.create_index('idx_clean_listings_preco_m2', 'clean_listings', ['preco_por_m2'])
    op.create_index('idx_clean_listings_area', 'clean_listings', ['area_util_m2'])
    op.create_index('idx_clean_listings_tipologia', 'clean_listings', ['tipologia'])
    
    # Valuations table
    op.create_table(
        'valuations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('listing_id', sa.String(), nullable=False),
        sa.Column('valor_justo', sa.Float(), nullable=True),
        sa.Column('hedonic_value', sa.Float(), nullable=True),
        sa.Column('comps_value', sa.Float(), nullable=True),
        sa.Column('ine_value', sa.Float(), nullable=True),
        sa.Column('xgboost_value', sa.Float(), nullable=True),
        sa.Column('xgboost_explanation', sa.JSON(), nullable=True),
        sa.Column('ci_lower', sa.Float(), nullable=True),
        sa.Column('ci_upper', sa.Float(), nullable=True),
        sa.Column('discount', sa.Float(), nullable=True),
        sa.Column('confianca', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['clean_listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_valuations_listing_id', 'valuations', ['listing_id'])
    op.create_index('idx_valuations_valor_justo', 'valuations', ['valor_justo'])
    
    # Scores table
    op.create_table(
        'scores',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('listing_id', sa.String(), nullable=False),
        sa.Column('score_total', sa.Float(), nullable=False),
        sa.Column('score_discount', sa.Float(), nullable=True),
        sa.Column('score_location', sa.Float(), nullable=True),
        sa.Column('score_condition', sa.Float(), nullable=True),
        sa.Column('score_liquidity', sa.Float(), nullable=True),
        sa.Column('score_freshness', sa.Float(), nullable=True),
        sa.Column('classificacao', sa.String(), nullable=True),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('red_flags', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['clean_listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scores_listing_id', 'scores', ['listing_id'])
    op.create_index('idx_scores_score_total', 'scores', ['score_total'])
    
    # Price history table
    op.create_table(
        'price_history',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('listing_id', sa.String(), nullable=False),
        sa.Column('preco', sa.Float(), nullable=False),
        sa.Column('data', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['clean_listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_listing_id', 'price_history', ['listing_id'])
    op.create_index('idx_price_history_data', 'price_history', ['data'])
    
    # Notifications table
    op.create_table(
        'notifications',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('listing_id', sa.String(), nullable=False),
        sa.Column('telegram_chat_id', sa.String(), nullable=True),
        sa.Column('telegram_message_id', sa.String(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['clean_listings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_listing_id', 'notifications', ['listing_id'])
    op.create_index('idx_notifications_status', 'notifications', ['status'])
    
    # Geocoding cache table
    op.create_table(
        'geocoding_cache',
        sa.Column('address_hash', sa.String(), nullable=False),
        sa.Column('address_raw', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('concelho', sa.String(), nullable=True),
        sa.Column('freguesia', sa.String(), nullable=True),
        sa.Column('precision', sa.String(), nullable=True),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('cached_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('address_hash')
    )
    
    # INE data table
    op.create_table(
        'ine_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('concelho', sa.String(), nullable=False),
        sa.Column('tipo_imovel', sa.String(), nullable=True),
        sa.Column('ano', sa.Integer(), nullable=True),
        sa.Column('trimestre', sa.Integer(), nullable=True),
        sa.Column('preco_mediano_m2', sa.Float(), nullable=True),
        sa.Column('variacao_homologa_pct', sa.Float(), nullable=True),
        sa.Column('num_transacoes', sa.Integer(), nullable=True),
        sa.Column('fonte', sa.String(), nullable=True),
        sa.Column('fetched_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ine_data_concelho', 'ine_data', ['concelho'])
    
    # System metrics table
    op.create_table(
        'system_metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('metric_name', sa.String(), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=True),
        sa.Column('metric_text', sa.Text(), nullable=True),
        sa.Column('portal', sa.String(), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Config table
    op.create_table(
        'config',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('key')
    )
    
    # Job execution log table
    op.create_table(
        'job_execution_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_name', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('records_processed', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_log_job_name', 'job_execution_log', ['job_name'])
    op.create_index('idx_job_log_started_at', 'job_execution_log', ['started_at'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_log_started_at', table_name='job_execution_log')
    op.drop_index('idx_job_log_job_name', table_name='job_execution_log')
    op.drop_table('job_execution_log')
    
    op.drop_table('config')
    
    op.drop_table('system_metrics')
    
    op.drop_index('idx_ine_data_concelho', table_name='ine_data')
    op.drop_table('ine_data')
    
    op.drop_table('geocoding_cache')
    
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_index('idx_notifications_listing_id', table_name='notifications')
    op.drop_table('notifications')
    
    op.drop_index('idx_price_history_data', table_name='price_history')
    op.drop_index('idx_price_history_listing_id', table_name='price_history')
    op.drop_table('price_history')
    
    op.drop_index('idx_scores_score_total', table_name='scores')
    op.drop_index('idx_scores_listing_id', table_name='scores')
    op.drop_table('scores')
    
    op.drop_index('idx_valuations_valor_justo', table_name='valuations')
    op.drop_index('idx_valuations_listing_id', table_name='valuations')
    op.drop_table('valuations')
    
    op.drop_index('idx_clean_listings_tipologia', table_name='clean_listings')
    op.drop_index('idx_clean_listings_area', table_name='clean_listings')
    op.drop_index('idx_clean_listings_preco_m2', table_name='clean_listings')
    op.drop_index('idx_clean_listings_preco', table_name='clean_listings')
    op.drop_index('idx_clean_listings_concelho', table_name='clean_listings')
    op.drop_index('idx_clean_listings_freguesia', table_name='clean_listings')
    op.drop_index('idx_clean_listings_source_portal', table_name='clean_listings')
    op.drop_table('clean_listings')
    
    op.drop_index('idx_raw_listings_source_id', table_name='raw_listings')
    op.drop_index('idx_raw_listings_scrape_timestamp', table_name='raw_listings')
    op.drop_index('idx_raw_listings_source_portal', table_name='raw_listings')
    op.drop_table('raw_listings')
    # ### end Alembic commands ###
