"""add_missing_clean_listings_columns

Revision ID: 002_add_missing
Revises: 001_initial
Create Date: 2026-05-05 01:46:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_missing'
down_revision: Union[str, Sequence[str], None] = '9725d9bc3cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add missing columns to clean_listings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Only add columns that are actually missing (verified against current schema)
    # Missing: area_bruta_m2, morada, certificado_energetico, fotos
    op.add_column('clean_listings', sa.Column('area_bruta_m2', sa.Float(), nullable=True))
    op.add_column('clean_listings', sa.Column('morada', sa.Text(), nullable=True))
    op.add_column('clean_listings', sa.Column('certificado_energetico', sa.String(), nullable=True))
    op.add_column('clean_listings', sa.Column('fotos', sa.JSON(), nullable=True))
    
    # Create indexes for new columns (if they don't exist)
    try:
        op.create_index('idx_image_phash', 'clean_listings', ['image_phash'])
    except Exception:
        pass
    try:
        op.create_index('idx_bert_sentiment', 'clean_listings', ['bert_sentiment_score'])
    except Exception:
        pass
    try:
        op.create_index('idx_image_quality', 'clean_listings', ['image_quality_score'])
    except Exception:
        pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove added columns from clean_listings table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    try:
        op.drop_index('idx_image_quality', table_name='clean_listings')
    except Exception:
        pass
    try:
        op.drop_index('idx_bert_sentiment', table_name='clean_listings')
    except Exception:
        pass
    try:
        op.drop_index('idx_image_phash', table_name='clean_listings')
    except Exception:
        pass
    
    # Drop columns
    op.drop_column('clean_listings', 'fotos')
    op.drop_column('clean_listings', 'certificado_energetico')
    op.drop_column('clean_listings', 'morada')
    op.drop_column('clean_listings', 'area_bruta_m2')
    
    # ### end Alembic commands ###
